# Generated by Django 4.1.7 on 2023-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('ECE', 'Electronics and Communication'), ('DSC', 'Data Science')], max_length=200),
        ),
    ]
