# Generated by Django 4.1.7 on 2023-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_course_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sem',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=20),
        ),
    ]
