# Generated by Django 4.1.7 on 2023-03-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_course_sem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='mod_no',
            new_name='modno',
        ),
    ]
