# Generated by Django 4.1.7 on 2023-03-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_mod_no_module_modno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='modno',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
