# Generated by Django 4.1.7 on 2023-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_module_modno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='modno',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('modno', 'course'), name='unique_course_module'),
        ),
    ]
