# Generated by Django 4.1.7 on 2023-03-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_module_modno_module_unique_course_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
