# Generated by Django 4.1.7 on 2023-03-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('marks', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=200)),
                ('rbt_level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=200)),
                ('qtype', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=200)),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.module')),
            ],
        ),
    ]
