# Generated by Django 4.1.7 on 2023-03-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_question_qtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='modules',
            new_name='module',
        ),
    ]
