# Generated by Django 4.1.7 on 2023-03-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_question_option1_remove_question_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='marks',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.CharField(choices=[('8', '8'), ('16', '16')], max_length=200),
        ),
    ]
