# Generated by Django 4.1.7 on 2023-03-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_module_modno'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ccode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
