# Generated by Django 4.1.7 on 2023-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_course_ccode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ccode',
            field=models.CharField(default='MVJ', max_length=200),
        ),
    ]
