# Generated by Django 4.1.7 on 2023-03-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_course_ccode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
