# Generated by Django 4.1.7 on 2023-03-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='qp',
            field=models.TextField(),
        ),
    ]
