# Generated by Django 4.1.7 on 2023-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_paper_qp'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
