# Generated by Django 4.1.7 on 2023-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_paper_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20),
        ),
    ]
